INSERT INTO verse_translations (verse_id, bible_translation_id, verse_text)
SELECT mv.id, 1, t.verse_text
FROM (VALUES
  ('2026-01-01'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-01-02'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-01-03'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-01-04'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-01-05'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-01-06'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-01-07'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-01-08'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-01-09'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-01-10'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-01-11'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-01-12'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-01-13'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-01-14'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-01-15'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-01-16'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-01-17'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-01-18'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-01-19'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-01-20'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-01-21'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-01-22'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-01-23'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-01-24'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-01-25'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-01-26'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-01-27'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-01-28'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-01-29'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-01-30'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-01-31'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-02-01'::date, 3, 'Delight yourself in the LORD, and he will give you the desires of your heart.'),
  ('2026-02-02'::date, 3, 'But they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.'),
  ('2026-02-03'::date, 3, 'For I know the plans I have for you, declares the LORD, plans for welfare and not for evil, to give you a future and a hope.'),
  ('2026-02-04'::date, 3, 'Come to me, all who labor and are heavy laden, and I will give you rest.'),
  ('2026-02-05'::date, 3, 'Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.'),
  ('2026-02-06'::date, 3, 'And we know that for those who love God all things work together for good, for those who are called according to his purpose.'),
  ('2026-02-07'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.'),
  ('2026-02-08'::date, 3, 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law.'),
  ('2026-02-09'::date, 3, 'Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.'),
  ('2026-02-10'::date, 3, 'And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.'),
  ('2026-02-11'::date, 3, 'So as to walk in a manner worthy of the Lord, fully pleasing to him: bearing fruit in every good work and increasing in the knowledge of God.'),
  ('2026-02-12'::date, 3, 'Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.'),
  ('2026-02-13'::date, 3, 'For God gave us a spirit not of fear but of power and love and self-control.'),
  ('2026-02-14'::date, 3, 'Looking to Jesus, the founder and perfecter of our faith, who for the joy that was set before him endured the cross.'),
  ('2026-02-15'::date, 3, 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.'),
  ('2026-02-16'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-02-17'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-02-18'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-02-19'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-02-20'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-02-21'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-02-22'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-02-23'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-02-24'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-02-25'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-02-26'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-02-27'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-02-28'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-03-01'::date, 3, 'God is our refuge and strength, a very present help in trouble.'),
  ('2026-03-02'::date, 3, 'When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you.'),
  ('2026-03-03'::date, 3, 'For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.'),
  ('2026-03-04'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.'),
  ('2026-03-05'::date, 3, 'Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.'),
  ('2026-03-06'::date, 3, 'And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.'),
  ('2026-03-07'::date, 3, 'So as to walk in a manner worthy of the Lord, fully pleasing to him: bearing fruit in every good work and increasing in the knowledge of God.'),
  ('2026-03-08'::date, 3, 'Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.'),
  ('2026-03-09'::date, 3, 'For God gave us a spirit not of fear but of power and love and self-control.'),
  ('2026-03-10'::date, 3, 'Looking to Jesus, the founder and perfecter of our faith, who for the joy that was set before him endured the cross.'),
  ('2026-03-11'::date, 3, 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.'),
  ('2026-03-12'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-03-13'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-03-14'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-03-15'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-03-16'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-03-17'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-03-18'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-03-19'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-03-20'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-03-21'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-03-22'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-03-23'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-03-24'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-03-25'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-03-26'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-03-27'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-03-28'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-03-29'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-03-30'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-03-31'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-04-01'::date, 3, 'The LORD is near to the brokenhearted and saves the crushed in spirit.'),
  ('2026-04-02'::date, 3, 'For I, the LORD your God, hold your right hand; it is I who say to you, "Fear not, I am the one who helps you."'),
  ('2026-04-03'::date, 3, 'Blessed is the man who trusts in the LORD, whose trust is the LORD.'),
  ('2026-04-04'::date, 3, 'Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.'),
  ('2026-04-05'::date, 3, 'I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.'),
  ('2026-04-06'::date, 3, 'There is therefore now no condemnation for those who are in Christ Jesus.'),
  ('2026-04-07'::date, 3, 'Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, so that we may be able to comfort those who are in any affliction, with the comfort with which we ourselves are comforted by God.'),
  ('2026-04-08'::date, 3, 'And let us not grow weary of doing good, for in due season we will reap, if we do not give up.'),
  ('2026-04-09'::date, 3, 'Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.'),
  ('2026-04-10'::date, 3, 'But you are a chosen race, a royal priesthood, a holy nation, a people for his own possession, that you may proclaim the excellencies of him who called you out of darkness into his marvelous light.'),
  ('2026-04-11'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.'),
  ('2026-04-12'::date, 3, 'Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.'),
  ('2026-04-13'::date, 3, 'And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.'),
  ('2026-04-14'::date, 3, 'So as to walk in a manner worthy of the Lord, fully pleasing to him: bearing fruit in every good work and increasing in the knowledge of God.'),
  ('2026-04-15'::date, 3, 'Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.'),
  ('2026-04-16'::date, 3, 'For God gave us a spirit not of fear but of power and love and self-control.'),
  ('2026-04-17'::date, 3, 'Looking to Jesus, the founder and perfecter of our faith, who for the joy that was set before him endured the cross.'),
  ('2026-04-18'::date, 3, 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.'),
  ('2026-04-19'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-04-20'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-04-21'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-04-22'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-04-23'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-04-24'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-04-25'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-04-26'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-04-27'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-04-28'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-04-29'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-04-30'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-05-01'::date, 3, 'Delight yourself in the LORD, and he will give you the desires of your heart.'),
  ('2026-05-02'::date, 3, 'But they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.'),
  ('2026-05-03'::date, 3, 'For I know the plans I have for you, declares the LORD, plans for welfare and not for evil, to give you a future and a hope.'),
  ('2026-05-04'::date, 3, 'Come to me, all who labor and are heavy laden, and I will give you rest.'),
  ('2026-05-05'::date, 3, 'Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.'),
  ('2026-05-06'::date, 3, 'And we know that for those who love God all things work together for good, for those who are called according to his purpose.'),
  ('2026-05-07'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.'),
  ('2026-05-08'::date, 3, 'Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.'),
  ('2026-05-09'::date, 3, 'And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.'),
  ('2026-05-10'::date, 3, 'So as to walk in a manner worthy of the Lord, fully pleasing to him: bearing fruit in every good work and increasing in the knowledge of God.'),
  ('2026-05-11'::date, 3, 'Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.'),
  ('2026-05-12'::date, 3, 'For God gave us a spirit not of fear but of power and love and self-control.'),
  ('2026-05-13'::date, 3, 'Looking to Jesus, the founder and perfecter of our faith, who for the joy that was set before him endured the cross.'),
  ('2026-05-14'::date, 3, 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.'),
  ('2026-05-15'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-05-16'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-05-17'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-05-18'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-05-19'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-05-20'::date, 3, 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
  ('2026-05-21'::date, 3, 'For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.'),
  ('2026-05-22'::date, 3, 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-05-23'::date, 3, 'But God shows his love for us in that while we were still sinners, Christ died for us.'),
  ('2026-05-24'::date, 3, 'So now faith, hope, and love abide, these three; but the greatest of these is love.'),
  ('2026-05-25'::date, 3, 'Now faith is the assurance of things hoped for, the conviction of things not seen.'),
  ('2026-05-26'::date, 3, 'Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.'),
  ('2026-05-27'::date, 3, 'Casting all your anxieties on him, because he cares for you.'),
  ('2026-05-28'::date, 3, 'His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence.'),
  ('2026-05-29'::date, 3, 'If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.'),
  ('2026-05-30'::date, 3, 'Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me.'),
  ('2026-05-31'::date, 3, 'The LORD is my shepherd; I shall not want.'),
  ('2026-06-01'::date, 3, 'I lift up my eyes to the hills. From where does my help come? My help comes from the LORD, who made heaven and earth.'),
  ('2026-06-02'::date, 3, 'Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.'),
  ('2026-06-03'::date, 3, 'The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.'),
  ('2026-06-04'::date, 3, 'But seek first the kingdom of God and his righteousness, and all these things will be added to you.'),
  ('2026-06-05'::date, 3, 'I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit, for apart from me you can do nothing.'),
  ('2026-06-06'::date, 3, 'Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.'),
  ('2026-06-07'::date, 3, 'No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape, that you may be able to endure it.'),
  ('2026-06-08'::date, 3, 'For freedom Christ has set us free; stand firm therefore, and do not submit again to a yoke of slavery.'),
  ('2026-06-09'::date, 3, 'Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you.'),
  ('2026-06-10'::date, 3, 'For it is God who works in you, both to will and to work for his good pleasure.'),
  ('2026-06-11'::date, 3, 'Whatever you do, work heartily, as for the Lord and not for men.'),
  ('2026-06-12'::date, 3, 'But godliness with contentment is great gain.'),
  ('2026-06-13'::date, 3, 'Do your best to present yourself to God as one approved, a worker who has no need to be ashamed, rightly handling the word of truth.'),
  ('2026-06-14'::date, 3, 'He saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit.'),
  ('2026-06-15'::date, 3, 'Keep your life free from love of money, and be content with what you have, for he has said, "I will never leave you nor forsake you."'),
  ('2026-06-16'::date, 3, 'Submit yourselves therefore to God. Resist the devil, and he will flee from you.'),
  ('2026-06-17'::date, 3, 'In this you rejoice, though now for a little while, if necessary, you have been grieved by various trials, so that the tested genuineness of your faith—more precious than gold that perishes though it is tested by fire—may be found to result in praise and glory and honor at the revelation of Jesus Christ.'),
  ('2026-06-18'::date, 3, 'The LORD is near to the brokenhearted and saves the crushed in spirit.'),
  ('2026-06-19'::date, 3, 'For I, the LORD your God, hold your right hand; it is I who say to you, "Fear not, I am the one who helps you."'),
  ('2026-06-20'::date, 3, 'Blessed is the man who trusts in the LORD, whose trust is the LORD.'),
  ('2026-06-21'::date, 3, 'Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.'),
  ('2026-06-22'::date, 3, 'I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.'),
  ('2026-06-23'::date, 3, 'There is therefore now no condemnation for those who are in Christ Jesus.'),
  ('2026-06-24'::date, 3, 'Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, so that we may be able to comfort those who are in any affliction, with the comfort with which we ourselves are comforted by God.'),
  ('2026-06-25'::date, 3, 'And let us not grow weary of doing good, for in due season we will reap, if we do not give up.'),
  ('2026-06-26'::date, 3, 'Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.'),
  ('2026-06-27'::date, 3, 'But you are a chosen race, a royal priesthood, a holy nation, a people for his own possession, that you may proclaim the excellencies of him who called you out of darkness into his marvelous light.'),
  ('2026-06-28'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly of my weaknesses, so that the power of Christ may rest upon me.'),
  ('2026-06-29'::date, 3, 'Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.'),
  ('2026-06-30'::date, 3, 'And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.')
) AS t(verse_date, age_group_id, verse_text)
JOIN memory_verses mv ON mv.verse_date = t.verse_date AND mv.age_group_id = t.age_group_id;