INSERT INTO verse_translations (verse_id, bible_translation_id, verse_text)
SELECT mv.id, 1, t.verse_text
FROM (VALUES
  ('2026-07-01'::date, 3, 'Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting!'),
  ('2026-07-02'::date, 3, 'You keep him in perfect peace whose mind is stayed on you, because he trusts in you.'),
  ('2026-07-03'::date, 3, 'Teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.'),
  ('2026-07-04'::date, 3, 'What then shall we say to these things? If God is for us, who can be against us?'),
  ('2026-07-05'::date, 3, 'But, as it is written, "What no eye has seen, nor ear heard, nor the heart of man imagined, what God has prepared for those who love him."'),
  ('2026-07-06'::date, 3, 'So we do not lose heart. Though our outer self is wasting away, our inner self is being renewed day by day. For this light momentary affliction is preparing for us an eternal weight of glory beyond all comparison.'),
  ('2026-07-07'::date, 3, 'I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.'),
  ('2026-07-08'::date, 3, 'Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places.'),
  ('2026-07-09'::date, 3, 'Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal for the prize of the upward call of God in Christ Jesus.'),
  ('2026-07-10'::date, 3, 'Therefore, as you received Christ Jesus the Lord, so walk in him, rooted and built up in him and established in the faith, just as you were taught, abounding in thanksgiving.'),
  ('2026-07-11'::date, 3, 'For this is the will of God, your sanctification.'),
  ('2026-07-12'::date, 3, 'But the Lord is faithful. He will establish you and guard you against the evil one.'),
  ('2026-07-13'::date, 3, 'For while bodily training is of some value, godliness is of value in every way, as it holds promise for the present life and also for the life to come.'),
  ('2026-07-14'::date, 3, 'All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness, that the man of God may be complete, equipped for every good work.'),
  ('2026-07-15'::date, 3, 'For the grace of God has appeared, bringing salvation for all people, training us to renounce ungodliness and worldly passions, and to live self-controlled, upright, and godly lives in the present age.'),
  ('2026-07-16'::date, 3, 'And let us consider how to stir up one another to love and good works, not neglecting to meet together, as is the habit of some, but encouraging one another, and all the more as you see the Day drawing near.'),
  ('2026-07-17'::date, 3, 'But the wisdom from above is first pure, then peaceable, gentle, open to reason, full of mercy and good fruits, impartial and sincere.'),
  ('2026-07-18'::date, 3, 'As each has received a gift, use it to serve one another, as good stewards of God’s varied grace.'),
  ('2026-07-19'::date, 3, 'But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To him be the glory both now and to the day of eternity. Amen.'),
  ('2026-07-20'::date, 3, 'We love because he first loved us.'),
  ('2026-07-21'::date, 3, 'He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.'),
  ('2026-07-22'::date, 3, 'Your word is a lamp to my feet and a light to my path.'),
  ('2026-07-23'::date, 3, 'The heart of man plans his way, but the LORD establishes his steps.'),
  ('2026-07-24'::date, 3, 'For everything there is a season, and a time for every matter under heaven.'),
  ('2026-07-25'::date, 3, 'For my thoughts are not your thoughts, neither are your ways my ways, declares the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.'),
  ('2026-07-26'::date, 3, 'Call to me and I will answer you, and will tell you great and hidden things that you have not known.'),
  ('2026-07-27'::date, 3, 'He has told you, O man, what is good; and what does the LORD require of you but to do justice, and to love kindness, and to walk humbly with your God?'),
  ('2026-07-28'::date, 3, 'Though the fig tree should not blossom, nor fruit be on the vines, the produce of the olive fail and the fields yield no food, the flock be cut off from the fold and there be no herd in the stalls, yet I will rejoice in the LORD; I will take joy in the God of my salvation.'),
  ('2026-07-29'::date, 3, 'The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.'),
  ('2026-07-30'::date, 3, 'Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!'),
  ('2026-07-31'::date, 3, 'When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you.'),
  ('2026-08-01'::date, 3, 'The sacrifices of God are a broken spirit; a broken and contrite heart, O God, you will not despise.'),
  ('2026-08-02'::date, 3, 'For thus said the Lord GOD, the Holy One of Israel, "In returning and rest you shall be saved; in quietness and in trust shall be your strength."'),
  ('2026-08-03'::date, 3, 'I have loved you with an everlasting love; therefore I have continued my faithfulness to you.'),
  ('2026-08-04'::date, 3, 'For I desire steadfast love and not sacrifice, the knowledge of God rather than burnt offerings.'),
  ('2026-08-05'::date, 3, 'In the same way, let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven.'),
  ('2026-08-06'::date, 3, 'And you shall love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength. The second is this: You shall love your neighbor as yourself. There is no other commandment greater than these.'),
  ('2026-08-07'::date, 3, 'Give, and it will be given to you. Good measure, pressed down, shaken together, running over, will be put into your lap. For with the measure you use it will be measured back to you.'),
  ('2026-08-08'::date, 3, 'A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another. By this all people will know that you are my disciples, if you have love for one another.'),
  ('2026-08-09'::date, 3, 'But I do not account my life of any value nor as precious to myself, if only I may finish my course and the ministry that I received from the Lord Jesus, to testify to the gospel of the grace of God.'),
  ('2026-08-10'::date, 3, 'May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope.'),
  ('2026-08-11'::date, 3, 'Therefore, my beloved brothers, be steadfast, immovable, always abounding in the work of the Lord, knowing that in the Lord your labor is not in vain.'),
  ('2026-08-12'::date, 3, 'And God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.'),
  ('2026-08-13'::date, 3, 'Bear one another''s burdens, and so fulfill the law of Christ.'),
  ('2026-08-14'::date, 3, 'Therefore be imitators of God, as beloved children. And walk in love, as Christ loved us and gave himself up for us, a fragrant offering and sacrifice to God.'),
  ('2026-08-15'::date, 3, 'And my God will supply every need of yours according to his riches in glory in Christ Jesus.'),
  ('2026-08-16'::date, 3, 'And whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God the Father through him.'),
  ('2026-08-17'::date, 3, 'He who calls you is faithful; he will surely do it.'),
  ('2026-08-18'::date, 3, 'Now may our Lord Jesus Christ himself, and God our Father, who loved us and gave us eternal comfort and good hope through grace, comfort your hearts and establish them in every good work and word.'),
  ('2026-08-19'::date, 3, 'But as for you, O man of God, flee these things. Pursue righteousness, godliness, faith, love, steadfastness, gentleness.'),
  ('2026-08-20'::date, 3, 'Therefore, since we are surrounded by so great a cloud of witnesses, let us also lay aside every weight, and sin which clings so closely, and let us run with endurance the race that is set before us.'),
  ('2026-08-21'::date, 3, 'Blessed is the man who remains steadfast under trial, for when he has stood the test he will receive the crown of life, which God has promised to those who love him.'),
  ('2026-08-22'::date, 3, 'Beloved, I urge you as sojourners and exiles to abstain from the passions of the flesh, which wage war against your soul.'),
  ('2026-08-23'::date, 3, 'Therefore, brothers, be all the more diligent to confirm your calling and election, for if you practice these qualities you will never fall.'),
  ('2026-08-24'::date, 3, 'See what kind of love the Father has given to us, that we should be called children of God; and so we are.'),
  ('2026-08-25'::date, 3, 'The Spirit and the Bride say, "Come." And let the one who hears say, "Come." And let the one who is thirsty come; let the one who desires take the water of life without price.'),
  ('2026-08-26'::date, 3, 'I have stored up your word in my heart, that I might not sin against you.'),
  ('2026-08-27'::date, 3, 'Keep your heart with all vigilance, for from it flow the springs of life.'),
  ('2026-08-28'::date, 3, 'The end of the matter; all has been heard. Fear God and keep his commandments, for this is the whole duty of man.'),
  ('2026-08-29'::date, 3, 'My beloved is mine, and I am his.'),
  ('2026-08-30'::date, 3, 'If this be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of your hand, O king. But if not, be it known to you, O king, that we will not serve your gods or worship the golden image that you have set up.'),
  ('2026-08-31'::date, 3, 'Behold, his soul is puffed up; it is not upright within him, but the righteous shall live by his faith.'),
  ('2026-09-01'::date, 3, 'I sought the LORD, and he answered me and delivered me from all my fears.'),
  ('2026-09-02'::date, 3, 'Have you not known? Have you not heard? The LORD is the everlasting God, the Creator of the ends of the earth. He does not faint or grow weary; his understanding is unsearchable. He gives power to the faint, and to him who has no might he increases strength.'),
  ('2026-09-03'::date, 3, 'Ah, Lord GOD! It is you who have made the heavens and the earth by your great power and by your outstretched arm! Nothing is too hard for you.'),
  ('2026-09-04'::date, 3, 'Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you.'),
  ('2026-09-05'::date, 3, 'The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.'),
  ('2026-09-06'::date, 3, 'Rejoice in hope, be patient in tribulation, be constant in prayer.'),
  ('2026-09-07'::date, 3, 'Be watchful, stand firm in the faith, act like men, be strong.'),
  ('2026-09-08'::date, 3, 'And we all, with unveiled face, beholding the glory of the Lord, are being transformed into the same image from one degree of glory to another. For this comes from the Lord who is the Spirit.'),
  ('2026-09-09'::date, 3, 'But I say, walk by the Spirit, and you will not gratify the desires of the flesh.'),
  ('2026-09-10'::date, 3, 'I therefore, a prisoner for the Lord, urge you to walk in a manner worthy of the calling to which you have been called.'),
  ('2026-09-11'::date, 3, 'Not that I have already obtained this or am already perfect, but I press on to make it my own, because Christ Jesus has made me his own.'),
  ('2026-09-12'::date, 3, 'Continue steadfastly in prayer, being watchful in it with thanksgiving.'),
  ('2026-09-13'::date, 3, 'Therefore encourage one another and build one another up, just as you are doing.'),
  ('2026-09-14'::date, 3, 'To this end we always pray for you, that our God may make you worthy of his calling and may fulfill every resolve for good and every work of faith by his power.'),
  ('2026-09-15'::date, 3, 'Let no one despise you for your youth, but set the believers an example in speech, in conduct, in love, in faith, in purity.'),
  ('2026-09-16'::date, 3, 'So flee youthful passions and pursue righteousness, faith, love, and peace, along with those who call on the Lord from a pure heart.'),
  ('2026-09-17'::date, 3, 'Show yourself in all respects to be a model of good works, and in your teaching show integrity, dignity.'),
  ('2026-09-18'::date, 3, 'And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.'),
  ('2026-09-19'::date, 3, 'Draw near to God, and he will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-minded.'),
  ('2026-09-20'::date, 3, 'Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour. Resist him, firm in your faith.'),
  ('2026-09-21'::date, 3, 'The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance.'),
  ('2026-09-22'::date, 3, 'And this is the confidence that we have toward him, that if we ask anything according to his will he hears us.'),
  ('2026-09-23'::date, 3, 'I know your works. Behold, I have set before you an open door, which no one is able to shut. I know that you have but little power, and yet you have kept my word and have not denied my name.'),
  ('2026-09-24'::date, 3, 'Your word is a lamp to my feet and a light to my path.'),
  ('2026-09-25'::date, 3, 'The heart of man plans his way, but the LORD establishes his steps.'),
  ('2026-09-26'::date, 3, 'For everything there is a season, and a time for every matter under heaven.'),
  ('2026-09-27'::date, 3, 'For my thoughts are not your thoughts, neither are your ways my ways, declares the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.'),
  ('2026-09-28'::date, 3, 'Call to me and I will answer you, and will tell you great and hidden things that you have not known.'),
  ('2026-09-29'::date, 3, 'He has told you, O man, what is good; and what does the LORD require of you but to do justice, and to love kindness, and to walk humbly with your God?'),
  ('2026-09-30'::date, 3, 'Though the fig tree should not blossom, nor fruit be on the vines, the produce of the olive fail and the fields yield no food, the flock be cut off from the fold and there be no herd in the stalls, yet I will rejoice in the LORD; I will take joy in the God of my salvation.'),
  ('2026-10-01'::date, 3, 'Commit your way to the LORD; trust in him, and he will act.'),
  ('2026-10-02'::date, 3, 'You keep him in perfect peace whose mind is stayed on you, because he trusts in you.'),
  ('2026-10-03'::date, 3, 'Ah, Lord GOD! It is you who have made the heavens and the earth by your great power and by your outstretched arm! Nothing is too hard for you.'),
  ('2026-10-04'::date, 3, 'Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you.'),
  ('2026-10-05'::date, 3, 'The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.'),
  ('2026-10-06'::date, 3, 'Rejoice in hope, be patient in tribulation, be constant in prayer.'),
  ('2026-10-07'::date, 3, 'Be watchful, stand firm in the faith, act like men, be strong.'),
  ('2026-10-08'::date, 3, 'And we all, with unveiled face, beholding the glory of the Lord, are being transformed into the same image from one degree of glory to another. For this comes from the Lord who is the Spirit.'),
  ('2026-10-09'::date, 3, 'But I say, walk by the Spirit, and you will not gratify the desires of the flesh.'),
  ('2026-10-10'::date, 3, 'I therefore, a prisoner for the Lord, urge you to walk in a manner worthy of the calling to which you have been called.'),
  ('2026-10-11'::date, 3, 'Not that I have already obtained this or am already perfect, but I press on to make it my own, because Christ Jesus has made me his own.'),
  ('2026-10-12'::date, 3, 'Continue steadfastly in prayer, being watchful in it with thanksgiving.'),
  ('2026-10-13'::date, 3, 'Therefore encourage one another and build one another up, just as you are doing.'),
  ('2026-10-14'::date, 3, 'To this end we always pray for you, that our God may make you worthy of his calling and may fulfill every resolve for good and every work of faith by his power.'),
  ('2026-10-15'::date, 3, 'Let no one despise you for your youth, but set the believers an example in speech, in conduct, in love, in faith, in purity.'),
  ('2026-10-16'::date, 3, 'So flee youthful passions and pursue righteousness, faith, love, and peace, along with those who call on the Lord from a pure heart.'),
  ('2026-10-17'::date, 3, 'Show yourself in all respects to be a model of good works, and in your teaching show integrity, dignity.'),
  ('2026-10-18'::date, 3, 'And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.'),
  ('2026-10-19'::date, 3, 'Draw near to God, and he will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-minded.'),
  ('2026-10-20'::date, 3, 'Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour. Resist him, firm in your faith.'),
  ('2026-10-21'::date, 3, 'The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance.'),
  ('2026-10-22'::date, 3, 'And this is the confidence that we have toward him, that if we ask anything according to his will he hears us.'),
  ('2026-10-23'::date, 3, 'I know your works. Behold, I have set before you an open door, which no one is able to shut. I know that you have but little power, and yet you have kept my word and have not denied my name.'),
  ('2026-10-24'::date, 3, 'I have stored up your word in my heart, that I might not sin against you.'),
  ('2026-10-25'::date, 3, 'Keep your heart with all vigilance, for from it flow the springs of life.'),
  ('2026-10-26'::date, 3, 'The end of the matter; all has been heard. Fear God and keep his commandments, for this is the whole duty of man.'),
  ('2026-10-27'::date, 3, 'My beloved is mine, and I am his.'),
  ('2026-10-28'::date, 3, 'If this be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of your hand, O king. But if not, be it known to you, O king, that we will not serve your gods or worship the golden image that you have set up.'),
  ('2026-10-29'::date, 3, 'Behold, his soul is puffed up; it is not upright within him, but the righteous shall live by his faith.'),
  ('2026-10-30'::date, 3, 'The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.'),
  ('2026-10-31'::date, 3, 'Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!'),
  ('2026-11-01'::date, 3, 'Wait for the LORD; be strong, and let your heart take courage; wait for the LORD!'),
  ('2026-11-02'::date, 3, 'Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.'),
  ('2026-11-03'::date, 3, 'Come to me, all who labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls. For my yoke is easy, and my burden is light.'),
  ('2026-11-04'::date, 3, 'No, in all these things we are more than conquerors through him who loved us.'),
  ('2026-11-05'::date, 3, 'And because of him you are in Christ Jesus, who became to us wisdom from God, righteousness and sanctification and redemption.'),
  ('2026-11-06'::date, 3, 'But we have this treasure in jars of clay, to show that the surpassing power belongs to God and not to us.'),
  ('2026-11-07'::date, 3, 'That according to the riches of his glory he may grant you to be strengthened with power through his Spirit in your inner being, so that Christ may dwell in your hearts through faith—that you, being rooted and grounded in love, may have strength to comprehend with all the saints what is the breadth and length and height and depth, and to know the love of Christ that surpasses knowledge, that you may be filled with all the fullness of God.'),
  ('2026-11-08'::date, 3, 'Finally, brothers, whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is commendable, if there is any excellence, if there is anything worthy of praise, think about these things.'),
  ('2026-11-09'::date, 3, 'Set your minds on things that are above, not on things that are on earth.'),
  ('2026-11-10'::date, 3, 'For this is the will of God, your sanctification.'),
  ('2026-11-11'::date, 3, 'May the Lord direct your hearts to the love of God and to the steadfastness of Christ.'),
  ('2026-11-12'::date, 3, 'The saying is trustworthy and deserving of full acceptance, that Christ Jesus came into the world to save sinners, of whom I am the foremost.'),
  ('2026-11-13'::date, 3, 'For this reason I suffer as I do. But I am not ashamed, for I know whom I have believed, and I am convinced that he is able to guard until that day what has been entrusted to me.'),
  ('2026-11-14'::date, 3, 'He saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit.'),
  ('2026-11-15'::date, 3, 'For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart.'),
  ('2026-11-16'::date, 3, 'Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom there is no variation or shadow due to change.'),
  ('2026-11-17'::date, 3, 'Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead.'),
  ('2026-11-18'::date, 3, 'By which he has granted to us his precious and very great promises, so that through them you may become partakers of the divine nature, having escaped from the corruption that is in the world because of sinful desire.'),
  ('2026-11-19'::date, 3, 'There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love.'),
  ('2026-11-20'::date, 3, 'When I saw him, I fell at his feet as though dead. But he laid his right hand on me, saying, "Fear not, I am the first and the last, and the living one. I died, and behold I am alive forevermore, and I have the keys of Death and Hades."'),
  ('2026-11-21'::date, 3, 'Bless the LORD, O my soul, and all that is within me, bless his holy name! Bless the LORD, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases, who redeems your life from the pit, who crowns you with steadfast love and mercy, who satisfies you with good so that your youth is renewed like the eagle’s.'),
  ('2026-11-22'::date, 3, 'Keep your heart with all vigilance, for from it flow the springs of life.'),
  ('2026-11-23'::date, 3, 'The end of the matter; all has been heard. Fear God and keep his commandments, for this is the whole duty of man.'),
  ('2026-11-24'::date, 3, 'My beloved is mine, and I am his.'),
  ('2026-11-25'::date, 3, 'If this be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of your hand, O king. But if not, be it known to you, O king, that we will not serve your gods or worship the golden image that you have set up.'),
  ('2026-11-26'::date, 3, 'Behold, his soul is puffed up; it is not upright within him, but the righteous shall live by his faith.'),
  ('2026-11-27'::date, 3, 'The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.'),
  ('2026-11-28'::date, 3, 'Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!'),
  ('2026-11-29'::date, 3, 'When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you.'),
  ('2026-11-30'::date, 3, 'I lift up my eyes to the hills. From where does my help come? My help comes from the LORD, who made heaven and earth.'),
  ('2026-12-01'::date, 3, 'O LORD, you have searched me and known me! You know when I sit down and when I rise up; you discern my thoughts from afar.'),
  ('2026-12-02'::date, 3, 'He gives power to the faint, and to him who has no might he increases strength.'),
  ('2026-12-03'::date, 3, 'You will seek me and find me, when you seek me with all your heart.'),
  ('2026-12-04'::date, 3, 'Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink, nor about your body, what you will put on. Is not life more than food, and the body more than clothing?'),
  ('2026-12-05'::date, 3, 'Fear not, little flock, for it is your Father''s good pleasure to give you the kingdom.'),
  ('2026-12-06'::date, 3, 'Let not your hearts be troubled. Believe in God; believe also in me.'),
  ('2026-12-07'::date, 3, 'He who did not spare his own Son but gave him up for us all, how will he not also with him graciously give us all things?'),
  ('2026-12-08'::date, 3, 'Love is patient and kind; love does not envy or boast; it is not arrogant or rude. It does not insist on its own way; it is not irritable or resentful; it does not rejoice at wrongdoing, but rejoices with the truth. Love bears all things, believes all things, hopes all things, endures all things.'),
  ('2026-12-09'::date, 3, 'As we look not to the things that are seen but to the things that are unseen. For the things that are seen are transient, but the things that are unseen are eternal.'),
  ('2026-12-10'::date, 3, 'I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.'),
  ('2026-12-11'::date, 3, 'Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.'),
  ('2026-12-12'::date, 3, 'Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal for the prize of the upward call of God in Christ Jesus.'),
  ('2026-12-13'::date, 3, 'Set your minds on things that are above, not on things that are on earth.'),
  ('2026-12-14'::date, 3, 'For this is the will of God, your sanctification.'),
  ('2026-12-15'::date, 3, 'May the Lord direct your hearts to the love of God and to the steadfastness of Christ.'),
  ('2026-12-16'::date, 3, 'The saying is trustworthy and deserving of full acceptance, that Christ Jesus came into the world to save sinners, of whom I am the foremost.'),
  ('2026-12-17'::date, 3, 'For this reason I suffer as I do. But I am not ashamed, for I know whom I have believed, and I am convinced that he is able to guard until that day what has been entrusted to me.'),
  ('2026-12-18'::date, 3, 'He saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit.'),
  ('2026-12-19'::date, 3, 'For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart.'),
  ('2026-12-20'::date, 3, 'Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom there is no variation or shadow due to change.'),
  ('2026-12-21'::date, 3, 'Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead.'),
  ('2026-12-22'::date, 3, 'By which he has granted to us his precious and very great promises, so that through them you may become partakers of the divine nature, having escaped from the corruption that is in the world because of sinful desire.'),
  ('2026-12-23'::date, 3, 'There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love.'),
  ('2026-12-24'::date, 3, 'When I saw him, I fell at his feet as though dead. But he laid his right hand on me, saying, "Fear not, I am the first and the last, and the living one. I died, and behold I am alive forevermore, and I have the keys of Death and Hades."'),
  ('2026-12-25'::date, 3, 'Bless the LORD, O my soul, and all that is within me, bless his holy name! Bless the LORD, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases, who redeems your life from the pit, who crowns you with steadfast love and mercy, who satisfies you with good so that your youth is renewed like the eagle’s.'),
  ('2026-12-26'::date, 3, 'Keep your heart with all vigilance, for from it flow the springs of life.'),
  ('2026-12-27'::date, 3, 'The end of the matter; all has been heard. Fear God and keep his commandments, for this is the whole duty of man.'),
  ('2026-12-28'::date, 3, 'My beloved is mine, and I am his.'),
  ('2026-12-29'::date, 3, 'If this be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of your hand, O king. But if not, be it known to you, O king, that we will not serve your gods or worship the golden image that you have set up.'),
  ('2026-12-30'::date, 3, 'Behold, his soul is puffed up; it is not upright within him, but the righteous shall live by his faith.'),
  ('2026-12-31'::date, 3, 'The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.')
) AS t(verse_date, age_group_id, verse_text)
JOIN memory_verses mv ON mv.verse_date = t.verse_date AND mv.age_group_id = t.age_group_id;