INSERT INTO verse_translations (verse_id, bible_translation_id, verse_text)
SELECT mv.id, 2, t.verse_text
FROM (VALUES
  ('2026-01-01'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-01-02'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-01-03'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-01-04'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-01-05'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-01-06'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-01-07'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-01-08'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-01-09'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-01-10'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-01-11'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-01-12'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-01-13'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-01-14'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-01-15'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-01-16'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-01-17'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-01-18'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-01-19'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-01-20'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-01-21'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-01-22'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-01-23'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-01-24'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-01-25'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-01-26'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-01-27'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-01-28'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-01-29'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-01-30'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-01-31'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-02-01'::date, 3, 'Take delight in the LORD, and he will give you the desires of your heart.'),
  ('2026-02-02'::date, 3, 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.'),
  ('2026-02-03'::date, 3, 'For I know the plans I have for you,” declares the LORD, “plans to prosper you and not to harm you, plans to give you hope and a future.'),
  ('2026-02-04'::date, 3, 'Come to me, all you who are weary and burdened, and I will give you rest.'),
  ('2026-02-05'::date, 3, 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.'),
  ('2026-02-06'::date, 3, 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.'),
  ('2026-02-07'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me.'),
  ('2026-02-08'::date, 3, 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.'),
  ('2026-02-09'::date, 3, 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.'),
  ('2026-02-10'::date, 3, 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.'),
  ('2026-02-11'::date, 3, 'So that you may live a life worthy of the Lord and please him in every way: bearing fruit in every good work, growing in the knowledge of God.'),
  ('2026-02-12'::date, 3, 'Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.'),
  ('2026-02-13'::date, 3, 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.'),
  ('2026-02-14'::date, 3, 'Fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross.'),
  ('2026-02-15'::date, 3, 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.'),
  ('2026-02-16'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-02-17'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-02-18'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-02-19'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-02-20'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-02-21'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-02-22'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-02-23'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-02-24'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-02-25'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-02-26'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-02-27'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-02-28'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-03-01'::date, 3, 'God is our refuge and strength, an ever-present help in trouble.'),
  ('2026-03-02'::date, 3, 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.'),
  ('2026-03-03'::date, 3, 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.'),
  ('2026-03-04'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me.'),
  ('2026-03-05'::date, 3, 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.'),
  ('2026-03-06'::date, 3, 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.'),
  ('2026-03-07'::date, 3, 'So that you may live a life worthy of the Lord and please him in every way: bearing fruit in every good work, growing in the knowledge of God.'),
  ('2026-03-08'::date, 3, 'Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.'),
  ('2026-03-09'::date, 3, 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.'),
  ('2026-03-10'::date, 3, 'Fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross.'),
  ('2026-03-11'::date, 3, 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.'),
  ('2026-03-12'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-03-13'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-03-14'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-03-15'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-03-16'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-03-17'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-03-18'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-03-19'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-03-20'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-03-21'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-03-22'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-03-23'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-03-24'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-03-25'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-03-26'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-03-27'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-03-28'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-03-29'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-03-30'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-03-31'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-04-01'::date, 3, 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.'),
  ('2026-04-02'::date, 3, 'For I am the LORD your God who takes hold of your right hand and says to you, Do not fear; I will help you.'),
  ('2026-04-03'::date, 3, 'But blessed is the one who trusts in the LORD, whose confidence is in him.'),
  ('2026-04-04'::date, 3, 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.'),
  ('2026-04-05'::date, 3, 'I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.'),
  ('2026-04-06'::date, 3, 'Therefore, there is now no condemnation for those who are in Christ Jesus.'),
  ('2026-04-07'::date, 3, 'Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles, so that we can comfort those in any trouble with the comfort we ourselves receive from God.'),
  ('2026-04-08'::date, 3, 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.'),
  ('2026-04-09'::date, 3, 'Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.'),
  ('2026-04-10'::date, 3, 'But you are a chosen people, a royal priesthood, a holy nation, God’s special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.'),
  ('2026-04-11'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me.'),
  ('2026-04-12'::date, 3, 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.'),
  ('2026-04-13'::date, 3, 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.'),
  ('2026-04-14'::date, 3, 'So that you may live a life worthy of the Lord and please him in every way: bearing fruit in every good work, growing in the knowledge of God.'),
  ('2026-04-15'::date, 3, 'Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.'),
  ('2026-04-16'::date, 3, 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.'),
  ('2026-04-17'::date, 3, 'Fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross.'),
  ('2026-04-18'::date, 3, 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.'),
  ('2026-04-19'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-04-20'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-04-21'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-04-22'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-04-23'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-04-24'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-04-25'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-04-26'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-04-27'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-04-28'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-04-29'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-04-30'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-05-01'::date, 3, 'Take delight in the LORD, and he will give you the desires of your heart.'),
  ('2026-05-02'::date, 3, 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.'),
  ('2026-05-03'::date, 3, 'For I know the plans I have for you,” declares the LORD, “plans to prosper you and not to harm you, plans to give you hope and a future.'),
  ('2026-05-04'::date, 3, 'Come to me, all you who are weary and burdened, and I will give you rest.'),
  ('2026-05-05'::date, 3, 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.'),
  ('2026-05-06'::date, 3, 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.'),
  ('2026-05-07'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me.'),
  ('2026-05-08'::date, 3, 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.'),
  ('2026-05-09'::date, 3, 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.'),
  ('2026-05-10'::date, 3, 'So that you may live a life worthy of the Lord and please him in every way: bearing fruit in every good work, growing in the knowledge of God.'),
  ('2026-05-11'::date, 3, 'Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.'),
  ('2026-05-12'::date, 3, 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.'),
  ('2026-05-13'::date, 3, 'Fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross.'),
  ('2026-05-14'::date, 3, 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.'),
  ('2026-05-15'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-05-16'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-05-17'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-05-18'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-05-19'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-05-20'::date, 3, 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
  ('2026-05-21'::date, 3, 'For we are God’s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
  ('2026-05-22'::date, 3, 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.'),
  ('2026-05-23'::date, 3, 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.'),
  ('2026-05-24'::date, 3, 'And now these three remain: faith, hope and love. But the greatest of these is love.'),
  ('2026-05-25'::date, 3, 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
  ('2026-05-26'::date, 3, 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
  ('2026-05-27'::date, 3, 'Cast all your anxiety on him because he cares for you.'),
  ('2026-05-28'::date, 3, 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.'),
  ('2026-05-29'::date, 3, 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
  ('2026-05-30'::date, 3, 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.'),
  ('2026-05-31'::date, 3, 'The LORD is my shepherd, I lack nothing.'),
  ('2026-06-01'::date, 3, 'I lift up my eyes to the mountains—where does my help come from? My help comes from the LORD, the Maker of heaven and earth.'),
  ('2026-06-02'::date, 3, 'Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.'),
  ('2026-06-03'::date, 3, 'Because of the LORD’s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.'),
  ('2026-06-04'::date, 3, 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.'),
  ('2026-06-05'::date, 3, 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.'),
  ('2026-06-06'::date, 3, 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is—his good, pleasing and perfect will.'),
  ('2026-06-07'::date, 3, 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.'),
  ('2026-06-08'::date, 3, 'It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.'),
  ('2026-06-09'::date, 3, 'Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.'),
  ('2026-06-10'::date, 3, 'For it is God who works in you to will and to act in order to fulfill his good purpose.'),
  ('2026-06-11'::date, 3, 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.'),
  ('2026-06-12'::date, 3, 'But godliness with contentment is great gain.'),
  ('2026-06-13'::date, 3, 'Do your best to present yourself to God as one approved, a worker who does not need to be ashamed and who correctly handles the word of truth.'),
  ('2026-06-14'::date, 3, 'He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit.'),
  ('2026-06-15'::date, 3, 'Keep your lives free from the love of money and be content with what you have, because God has said, "Never will I leave you; never will I forsake you."'),
  ('2026-06-16'::date, 3, 'Submit yourselves, then, to God. Resist the devil, and he will flee from you.'),
  ('2026-06-17'::date, 3, 'In all this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials. These have come so that the proven genuineness of your faith—of greater worth than gold, which perishes even though refined by fire—may result in praise, glory and honor when Jesus Christ is revealed.'),
  ('2026-06-18'::date, 3, 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.'),
  ('2026-06-19'::date, 3, 'For I am the LORD your God who takes hold of your right hand and says to you, Do not fear; I will help you.'),
  ('2026-06-20'::date, 3, 'But blessed is the one who trusts in the LORD, whose confidence is in him.'),
  ('2026-06-21'::date, 3, 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.'),
  ('2026-06-22'::date, 3, 'I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.'),
  ('2026-06-23'::date, 3, 'Therefore, there is now no condemnation for those who are in Christ Jesus.'),
  ('2026-06-24'::date, 3, 'Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles, so that we can comfort those in any trouble with the comfort we ourselves receive from God.'),
  ('2026-06-25'::date, 3, 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.'),
  ('2026-06-26'::date, 3, 'Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.'),
  ('2026-06-27'::date, 3, 'But you are a chosen people, a royal priesthood, a holy nation, God’s special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.'),
  ('2026-06-28'::date, 3, 'But he said to me, "My grace is sufficient for you, for my power is made perfect in weakness." Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me.'),
  ('2026-06-29'::date, 3, 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.'),
  ('2026-06-30'::date, 3, 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.')
) AS t(verse_date, age_group_id, verse_text)
JOIN memory_verses mv ON mv.verse_date = t.verse_date AND mv.age_group_id = t.age_group_id;