INSERT INTO verse_translations (verse_id, bible_translation_id, verse_text)
SELECT mv.id, 2, t.verse_text
FROM (VALUES
  ('2026-07-01'::date, 3, 'Search me, God, and know my heart; test me and know my anxious thoughts. See if there is any offensive way in me, and lead me in the way everlasting.'),
  ('2026-07-02'::date, 3, 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.'),
  ('2026-07-03'::date, 3, 'And teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age.'),
  ('2026-07-04'::date, 3, 'What, then, shall we say in response to these things? If God is for us, who can be against us?'),
  ('2026-07-05'::date, 3, 'However, as it is written: "What no eye has seen, what no ear has heard, and what no human mind has conceived"—the things God has prepared for those who love him.'),
  ('2026-07-06'::date, 3, 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day. For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.'),
  ('2026-07-07'::date, 3, 'I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.'),
  ('2026-07-08'::date, 3, 'Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.'),
  ('2026-07-09'::date, 3, 'Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.'),
  ('2026-07-10'::date, 3, 'So then, just as you received Christ Jesus as Lord, continue to live your lives in him, rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.'),
  ('2026-07-11'::date, 3, 'It is God’s will that you should be sanctified.'),
  ('2026-07-12'::date, 3, 'But the Lord is faithful, and he will strengthen you and protect you from the evil one.'),
  ('2026-07-13'::date, 3, 'For physical training is of some value, but godliness has value for all things, holding promise for both the present life and the life to come.'),
  ('2026-07-14'::date, 3, 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness, so that the servant of God may be thoroughly equipped for every good work.'),
  ('2026-07-15'::date, 3, 'For the grace of God has appeared that offers salvation to all people. It teaches us to say "No" to ungodliness and worldly passions, and to live self-controlled, upright and godly lives in this present age.'),
  ('2026-07-16'::date, 3, 'And let us consider how we may spur one another on toward love and good deeds, not giving up meeting together, as some are in the habit of doing, but encouraging one another—and all the more as you see the Day approaching.'),
  ('2026-07-17'::date, 3, 'But the wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive, full of mercy and good fruit, impartial and sincere.'),
  ('2026-07-18'::date, 3, 'Each of you should use whatever gift you have received to serve others, as faithful stewards of God’s grace in its various forms.'),
  ('2026-07-19'::date, 3, 'But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To him be glory both now and forever! Amen.'),
  ('2026-07-20'::date, 3, 'We love because he first loved us.'),
  ('2026-07-21'::date, 3, 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.'),
  ('2026-07-22'::date, 3, 'Your word is a lamp for my feet, a light on my path.'),
  ('2026-07-23'::date, 3, 'In their hearts humans plan their course, but the LORD establishes their steps.'),
  ('2026-07-24'::date, 3, 'There is a time for everything, and a season for every activity under the heavens.'),
  ('2026-07-25'::date, 3, 'For my thoughts are not your thoughts, neither are your ways my ways,” declares the LORD. “As the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.'),
  ('2026-07-26'::date, 3, 'Call to me and I will answer you and tell you great and unsearchable things you do not know.'),
  ('2026-07-27'::date, 3, 'He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.'),
  ('2026-07-28'::date, 3, 'Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food, though there are no sheep in the pen and no cattle in the stalls, yet I will rejoice in the LORD, I will be joyful in God my Savior.'),
  ('2026-07-29'::date, 3, 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.'),
  ('2026-07-30'::date, 3, 'He says, “Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.”'),
  ('2026-07-31'::date, 3, 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.'),
  ('2026-08-01'::date, 3, 'My sacrifice, O God, is a broken spirit; a broken and contrite heart you, God, will not despise.'),
  ('2026-08-02'::date, 3, 'This is what the Sovereign LORD, the Holy One of Israel, says: "In repentance and rest is your salvation, in quietness and trust is your strength."'),
  ('2026-08-03'::date, 3, 'I have loved you with an everlasting love; I have drawn you with unfailing kindness.'),
  ('2026-08-04'::date, 3, 'For I desire mercy, not sacrifice, and acknowledgment of God rather than burnt offerings.'),
  ('2026-08-05'::date, 3, 'In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.'),
  ('2026-08-06'::date, 3, 'Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength. The second is this: Love your neighbor as yourself. There is no commandment greater than these.'),
  ('2026-08-07'::date, 3, 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap. For with the measure you use, it will be measured to you.'),
  ('2026-08-08'::date, 3, 'A new command I give you: Love one another. As I have loved you, so you must love one another. By this everyone will know that you are my disciples, if you love one another.'),
  ('2026-08-09'::date, 3, 'However, I consider my life worth nothing to me; my only aim is to finish the race and complete the task the Lord Jesus has given me—the task of testifying to the good news of God’s grace.'),
  ('2026-08-10'::date, 3, 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.'),
  ('2026-08-11'::date, 3, 'Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.'),
  ('2026-08-12'::date, 3, 'And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.'),
  ('2026-08-13'::date, 3, 'Carry each other’s burdens, and in this way you will fulfill the law of Christ.'),
  ('2026-08-14'::date, 3, 'Follow God’s example, therefore, as dearly loved children and walk in the way of love, just as Christ loved us and gave himself up for us as a fragrant offering and sacrifice to God.'),
  ('2026-08-15'::date, 3, 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.'),
  ('2026-08-16'::date, 3, 'And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.'),
  ('2026-08-17'::date, 3, 'The one who calls you is faithful, and he will do it.'),
  ('2026-08-18'::date, 3, 'May our Lord Jesus Christ himself and God our Father, who loved us and by his grace gave us eternal encouragement and good hope, encourage your hearts and strengthen you in every good deed and word.'),
  ('2026-08-19'::date, 3, 'But you, man of God, flee from all this, and pursue righteousness, godliness, faith, love, endurance and gentleness.'),
  ('2026-08-20'::date, 3, 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us.'),
  ('2026-08-21'::date, 3, 'Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life that the Lord has promised to those who love him.'),
  ('2026-08-22'::date, 3, 'Dear friends, I urge you, as foreigners and exiles, to abstain from sinful desires, which wage war against your soul.'),
  ('2026-08-23'::date, 3, 'Therefore, my brothers and sisters, make every effort to confirm your calling and election. For if you do these things, you will never stumble.'),
  ('2026-08-24'::date, 3, 'See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!'),
  ('2026-08-25'::date, 3, 'The Spirit and the bride say, "Come!" And let the one who hears say, "Come!" Let the one who is thirsty come; and let the one who wishes take the free gift of the water of life.'),
  ('2026-08-26'::date, 3, 'I have hidden your word in my heart that I might not sin against you.'),
  ('2026-08-27'::date, 3, 'Above all else, guard your heart, for everything you do flows from it.'),
  ('2026-08-28'::date, 3, 'Now all has been heard; here is the conclusion of the matter: Fear God and keep his commandments, for this is the duty of all mankind.'),
  ('2026-08-29'::date, 3, 'My beloved is mine and I am his.'),
  ('2026-08-30'::date, 3, 'If we are thrown into the blazing furnace, the God we serve is able to deliver us from it, and he will deliver us from Your Majesty’s hand. But even if he does not, we want you to know, Your Majesty, that we will not serve your gods or worship the image of gold you have set up.'),
  ('2026-08-31'::date, 3, 'See, the enemy is puffed up; his desires are not upright—but the righteous person will live by his faithfulness.'),
  ('2026-09-01'::date, 3, 'I sought the LORD, and he answered me; he delivered me from all my fears.'),
  ('2026-09-02'::date, 3, 'Do you not know? Have you not heard? The LORD is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary, and his understanding no one can fathom. He gives strength to the weary and increases the power of the weak.'),
  ('2026-09-03'::date, 3, 'Ah, Sovereign LORD, you have made the heavens and the earth by your great power and outstretched arm. Nothing is too hard for you.'),
  ('2026-09-04'::date, 3, 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.'),
  ('2026-09-05'::date, 3, 'The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.'),
  ('2026-09-06'::date, 3, 'Be joyful in hope, patient in affliction, faithful in prayer.'),
  ('2026-09-07'::date, 3, 'Be on your guard; stand firm in the faith; be courageous; be strong.'),
  ('2026-09-08'::date, 3, 'And we all, who with unveiled faces contemplate the Lord’s glory, are being transformed into his image with ever-increasing glory, which comes from the Lord, who is the Spirit.'),
  ('2026-09-09'::date, 3, 'So I say, walk by the Spirit, and you will not gratify the desires of the flesh.'),
  ('2026-09-10'::date, 3, 'As a prisoner for the Lord, then, I urge you to live a life worthy of the calling you have received.'),
  ('2026-09-11'::date, 3, 'Not that I have already obtained all this, or have already arrived at my goal, but I press on to take hold of that for which Christ Jesus took hold of me.'),
  ('2026-09-12'::date, 3, 'Devote yourselves to prayer, being watchful and thankful.'),
  ('2026-09-13'::date, 3, 'Therefore encourage one another and build each other up, just as in fact you are doing.'),
  ('2026-09-14'::date, 3, 'With this in mind, we constantly pray for you, that our God may make you worthy of his calling, and that by his power he may bring to fruition your every desire for goodness and your every deed prompted by faith.'),
  ('2026-09-15'::date, 3, 'Don’t let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity.'),
  ('2026-09-16'::date, 3, 'Flee the evil desires of youth and pursue righteousness, faith, love and peace, along with those who call on the Lord out of a pure heart.'),
  ('2026-09-17'::date, 3, 'In everything set them an example by doing what is good. In your teaching show integrity, seriousness.'),
  ('2026-09-18'::date, 3, 'And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.'),
  ('2026-09-19'::date, 3, 'Come near to God and he will come near to you. Wash your hands, you sinners, and purify your hearts, you double-minded.'),
  ('2026-09-20'::date, 3, 'Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour. Resist him, standing firm in the faith.'),
  ('2026-09-21'::date, 3, 'The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance.'),
  ('2026-09-22'::date, 3, 'This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.'),
  ('2026-09-23'::date, 3, 'I know your deeds. See, I have placed before you an open door that no one can shut. I know that you have little strength, yet you have kept my word and have not denied my name.'),
  ('2026-09-24'::date, 3, 'Your word is a lamp for my feet, a light on my path.'),
  ('2026-09-25'::date, 3, 'In their hearts humans plan their course, but the LORD establishes their steps.'),
  ('2026-09-26'::date, 3, 'There is a time for everything, and a season for every activity under the heavens.'),
  ('2026-09-27'::date, 3, 'For my thoughts are not your thoughts, neither are your ways my ways,” declares the LORD. “As the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.'),
  ('2026-09-28'::date, 3, 'Call to me and I will answer you and tell you great and unsearchable things you do not know.'),
  ('2026-09-29'::date, 3, 'He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.'),
  ('2026-09-30'::date, 3, 'Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food, though there are no sheep in the pen and no cattle in the stalls, yet I will rejoice in the LORD, I will be joyful in God my Savior.'),
  ('2026-10-01'::date, 3, 'Commit your way to the LORD; trust in him and he will do this.'),
  ('2026-10-02'::date, 3, 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.'),
  ('2026-10-03'::date, 3, 'Ah, Sovereign LORD, you have made the heavens and the earth by your great power and outstretched arm. Nothing is too hard for you.'),
  ('2026-10-04'::date, 3, 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.'),
  ('2026-10-05'::date, 3, 'The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.'),
  ('2026-10-06'::date, 3, 'Be joyful in hope, patient in affliction, faithful in prayer.'),
  ('2026-10-07'::date, 3, 'Be on your guard; stand firm in the faith; be courageous; be strong.'),
  ('2026-10-08'::date, 3, 'And we all, who with unveiled faces contemplate the Lord’s glory, are being transformed into his image with ever-increasing glory, which comes from the Lord, who is the Spirit.'),
  ('2026-10-09'::date, 3, 'So I say, walk by the Spirit, and you will not gratify the desires of the flesh.'),
  ('2026-10-10'::date, 3, 'As a prisoner for the Lord, then, I urge you to live a life worthy of the calling you have received.'),
  ('2026-10-11'::date, 3, 'Not that I have already obtained all this, or have already arrived at my goal, but I press on to take hold of that for which Christ Jesus took hold of me.'),
  ('2026-10-12'::date, 3, 'Devote yourselves to prayer, being watchful and thankful.'),
  ('2026-10-13'::date, 3, 'Therefore encourage one another and build each other up, just as in fact you are doing.'),
  ('2026-10-14'::date, 3, 'With this in mind, we constantly pray for you, that our God may make you worthy of his calling, and that by his power he may bring to fruition your every desire for goodness and your every deed prompted by faith.'),
  ('2026-10-15'::date, 3, 'Don’t let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity.'),
  ('2026-10-16'::date, 3, 'Flee the evil desires of youth and pursue righteousness, faith, love and peace, along with those who call on the Lord out of a pure heart.'),
  ('2026-10-17'::date, 3, 'In everything set them an example by doing what is good. In your teaching show integrity, seriousness.'),
  ('2026-10-18'::date, 3, 'And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.'),
  ('2026-10-19'::date, 3, 'Come near to God and he will come near to you. Wash your hands, you sinners, and purify your hearts, you double-minded.'),
  ('2026-10-20'::date, 3, 'Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour. Resist him, standing firm in the faith.'),
  ('2026-10-21'::date, 3, 'The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance.'),
  ('2026-10-22'::date, 3, 'This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.'),
  ('2026-10-23'::date, 3, 'I know your deeds. See, I have placed before you an open door that no one can shut. I know that you have little strength, yet you have kept my word and have not denied my name.'),
  ('2026-10-24'::date, 3, 'I have hidden your word in my heart that I might not sin against you.'),
  ('2026-10-25'::date, 3, 'Above all else, guard your heart, for everything you do flows from it.'),
  ('2026-10-26'::date, 3, 'Now all has been heard; here is the conclusion of the matter: Fear God and keep his commandments, for this is the duty of all mankind.'),
  ('2026-10-27'::date, 3, 'My beloved is mine and I am his.'),
  ('2026-10-28'::date, 3, 'If we are thrown into the blazing furnace, the God we serve is able to deliver us from it, and he will deliver us from Your Majesty’s hand. But even if he does not, we want you to know, Your Majesty, that we will not serve your gods or worship the image of gold you have set up.'),
  ('2026-10-29'::date, 3, 'See, the enemy is puffed up; his desires are not upright—but the righteous person will live by his faithfulness.'),
  ('2026-10-30'::date, 3, 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.'),
  ('2026-10-31'::date, 3, 'He says, “Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.”'),
  ('2026-11-01'::date, 3, 'Wait for the LORD; be strong and take heart and wait for the LORD.'),
  ('2026-11-02'::date, 3, 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.'),
  ('2026-11-03'::date, 3, 'Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy and my burden is light.'),
  ('2026-11-04'::date, 3, 'No, in all these things we are more than conquerors through him who loved us.'),
  ('2026-11-05'::date, 3, 'It is because of him that you are in Christ Jesus, who has become for us wisdom from God—that is, our righteousness, holiness and redemption.'),
  ('2026-11-06'::date, 3, 'But we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us.'),
  ('2026-11-07'::date, 3, 'I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being, so that Christ may dwell in your hearts through faith. And I pray that you, being rooted and established in love, may have power, together with all the Lord’s holy people, to grasp how wide and long and high and deep is the love of Christ, and to know this love that surpasses knowledge—that you may be filled to the measure of all the fullness of God.'),
  ('2026-11-08'::date, 3, 'Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.'),
  ('2026-11-09'::date, 3, 'Set your minds on things above, not on earthly things.'),
  ('2026-11-10'::date, 3, 'It is God’s will that you should be sanctified.'),
  ('2026-11-11'::date, 3, 'May the Lord direct your hearts into God’s love and Christ’s perseverance.'),
  ('2026-11-12'::date, 3, 'Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners—of whom I am the worst.'),
  ('2026-11-13'::date, 3, 'That is why I am suffering as I am. Yet this is no cause for shame, because I know whom I have believed, and am convinced that he is able to guard what I have entrusted to him until that day.'),
  ('2026-11-14'::date, 3, 'He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit.'),
  ('2026-11-15'::date, 3, 'For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.'),
  ('2026-11-16'::date, 3, 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.'),
  ('2026-11-17'::date, 3, 'Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead.'),
  ('2026-11-18'::date, 3, 'Through these he has given us his very great and precious promises, so that through them you may participate in the divine nature, having escaped the corruption in the world caused by evil desires.'),
  ('2026-11-19'::date, 3, 'There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.'),
  ('2026-11-20'::date, 3, 'When I saw him, I fell at his feet as though dead. Then he placed his right hand on me and said: "Do not be afraid. I am the First and the Last. I am the Living One; I was dead, and now look, I am alive for ever and ever! And I hold the keys of death and Hades."'),
  ('2026-11-21'::date, 3, 'Praise the LORD, my soul; all my inmost being, praise his holy name. Praise the LORD, my soul, and forget not all his benefits—who forgives all your sins and heals all your diseases, who redeems your life from the pit and crowns you with love and compassion, who satisfies your desires with good things so that your youth is renewed like the eagle’s.'),
  ('2026-11-22'::date, 3, 'Above all else, guard your heart, for everything you do flows from it.'),
  ('2026-11-23'::date, 3, 'Now all has been heard; here is the conclusion of the matter: Fear God and keep his commandments, for this is the duty of all mankind.'),
  ('2026-11-24'::date, 3, 'My beloved is mine and I am his.'),
  ('2026-11-25'::date, 3, 'If we are thrown into the blazing furnace, the God we serve is able to deliver us from it, and he will deliver us from Your Majesty’s hand. But even if he does not, we want you to know, Your Majesty, that we will not serve your gods or worship the image of gold you have set up.'),
  ('2026-11-26'::date, 3, 'See, the enemy is puffed up; his desires are not upright—but the righteous person will live by his faithfulness.'),
  ('2026-11-27'::date, 3, 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.'),
  ('2026-11-28'::date, 3, 'He says, “Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.”'),
  ('2026-11-29'::date, 3, 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.'),
  ('2026-11-30'::date, 3, 'I lift up my eyes to the mountains—where does my help come from? My help comes from the LORD, the Maker of heaven and earth.'),
  ('2026-12-01'::date, 3, 'You have searched me, LORD, and you know me. You know when I sit and when I rise; you perceive my thoughts from afar.'),
  ('2026-12-02'::date, 3, 'He gives strength to the weary and increases the power of the weak.'),
  ('2026-12-03'::date, 3, 'You will seek me and find me when you seek me with all your heart.'),
  ('2026-12-04'::date, 3, 'Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?'),
  ('2026-12-05'::date, 3, 'Do not be afraid, little flock, for your Father has been pleased to give you the kingdom.'),
  ('2026-12-06'::date, 3, 'Do not let your hearts be troubled. You believe in God; believe also in me.'),
  ('2026-12-07'::date, 3, 'He who did not spare his own Son, but gave him up for us all—how will he not also, along with him, graciously give us all things?'),
  ('2026-12-08'::date, 3, 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.'),
  ('2026-12-09'::date, 3, 'So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal.'),
  ('2026-12-10'::date, 3, 'I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.'),
  ('2026-12-11'::date, 3, 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.'),
  ('2026-12-12'::date, 3, 'Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.'),
  ('2026-12-13'::date, 3, 'Set your minds on things above, not on earthly things.'),
  ('2026-12-14'::date, 3, 'It is God’s will that you should be sanctified.'),
  ('2026-12-15'::date, 3, 'May the Lord direct your hearts into God’s love and Christ’s perseverance.'),
  ('2026-12-16'::date, 3, 'Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners—of whom I am the worst.'),
  ('2026-12-17'::date, 3, 'That is why I am suffering as I am. Yet this is no cause for shame, because I know whom I have believed, and am convinced that he is able to guard what I have entrusted to him until that day.'),
  ('2026-12-18'::date, 3, 'He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit.'),
  ('2026-12-19'::date, 3, 'For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.'),
  ('2026-12-20'::date, 3, 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.'),
  ('2026-12-21'::date, 3, 'Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead.'),
  ('2026-12-22'::date, 3, 'Through these he has given us his very great and precious promises, so that through them you may participate in the divine nature, having escaped the corruption in the world caused by evil desires.'),
  ('2026-12-23'::date, 3, 'There is no fear in love. But perfect love drives out fear, because fear has to do with punishment. The one who fears is not made perfect in love.'),
  ('2026-12-24'::date, 3, 'When I saw him, I fell at his feet as though dead. Then he placed his right hand on me and said: "Do not be afraid. I am the First and the Last. I am the Living One; I was dead, and now look, I am alive for ever and ever! And I hold the keys of death and Hades."'),
  ('2026-12-25'::date, 3, 'Praise the LORD, my soul; all my inmost being, praise his holy name. Praise the LORD, my soul, and forget not all his benefits—who forgives all your sins and heals all your diseases, who redeems your life from the pit and crowns you with love and compassion, who satisfies your desires with good things so that your youth is renewed like the eagle’s.'),
  ('2026-12-26'::date, 3, 'Above all else, guard your heart, for everything you do flows from it.'),
  ('2026-12-27'::date, 3, 'Now all has been heard; here is the conclusion of the matter: Fear God and keep his commandments, for this is the duty of all mankind.'),
  ('2026-12-28'::date, 3, 'My beloved is mine and I am his.'),
  ('2026-12-29'::date, 3, 'If we are thrown into the blazing furnace, the God we serve is able to deliver us from it, and he will deliver us from Your Majesty’s hand. But even if he does not, we want you to know, Your Majesty, that we will not serve your gods or worship the image of gold you have set up.'),
  ('2026-12-30'::date, 3, 'See, the enemy is puffed up; his desires are not upright—but the righteous person will live by his faithfulness.'),
  ('2026-12-31'::date, 3, 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.')
) AS t(verse_date, age_group_id, verse_text)
JOIN memory_verses mv ON mv.verse_date = t.verse_date AND mv.age_group_id = t.age_group_id;